model_name_or_path: /root/autodl-tmp/apr-rl/Qwen2.5-Coder-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
#attn_implementation: flash_attention_2
attn_implementation: sdpa
train_dataset: /root/autodl-tmp/apr-rl/data/apr_train_fold_1.jsonl
eval_dataset: /root/autodl-tmp/apr-rl/data/apr_test_fold_1.jsonl
do_eval: true
eval_strategy: steps
eval_steps: 500
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-05
log_level: info
logging_steps: 1
num_train_epochs: 1
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 1
output_dir: /root/autodl-tmp/apr-rl/Qwen2.5-1.5B-Instruct-APR-SFT
push_to_hub: False
report_to:
- tensorboard
save_strategy: 'epoch'
#save_steps: 250
#save_total_limit: 1
seed: 42
